# Generated by Django 5.0.3 on 2024-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Названия')),
                ('description', models.TextField(verbose_name='Описания')),
                ('feature_image', models.ImageField(default='default-services.jpg', upload_to='entertainment/%Y/%m/%d', verbose_name='Изображения')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(default=10000, verbose_name='Цена за позицию')),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'развлечение',
                'verbose_name_plural': 'Развлечения',
            },
        ),
        migrations.CreateModel(
            name='InfoSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Описание слайда')),
                ('image_slider', models.ImageField(upload_to='slider_images/%Y/%m/%d', verbose_name='Изображения слайда')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Названия')),
                ('description', models.TextField(verbose_name='Описания')),
                ('feature_image', models.ImageField(default='default-services.jpg', upload_to='menu/%Y/%m/%d', verbose_name='Изображения')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена за позицию')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Названия')),
                ('description', models.TextField(verbose_name='Описания')),
                ('feature_image', models.ImageField(default='default-services.jpg', upload_to='services/%Y/%m/%d', verbose_name='Изображения')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(default=10000, verbose_name='Цена за позицию/руб.')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='mainapp.tag')),
            ],
            options={
                'verbose_name': 'дом',
                'verbose_name_plural': 'Дома',
            },
        ),
    ]
