# Generated by Django 4.2.7 on 2024-02-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('feature_image', models.ImageField(default='default-services.jpj', upload_to='services/%Y/%m/%d')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(default=10000)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='mainapp.tag')),
            ],
        ),
    ]
