# Generated by Django 4.2.7 on 2024-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('image_slider', models.ImageField(upload_to='slider_images/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='feature_image',
            field=models.ImageField(default='default-services.jpg', upload_to='services/%Y/%m/%d'),
        ),
    ]
