# Generated by Django 4.2.7 on 2024-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_infoslider_alter_services_feature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('feature_image', models.ImageField(default='default-services.jpg', upload_to='services/%Y/%m/%d')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(default=10000)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('feature_image', models.ImageField(default='default-services.jpg', upload_to='services/%Y/%m/%d')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(default=10000)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
