# Generated by Django 4.2.7 on 2024-02-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_entertainment_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='feature_image',
            field=models.ImageField(default='default-services.jpg', upload_to='menu/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
