# Generated by Django 4.2.7 on 2024-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_menu_feature_image_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='feature_image',
            field=models.ImageField(default='default-services.jpg', upload_to='entertainment/%Y/%m/%d'),
        ),
    ]
