# Generated by Django 4.2.7 on 2024-03-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_entertainment_feature_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entertainment',
            options={'verbose_name': 'развлечение', 'verbose_name_plural': 'Развлечения'},
        ),
        migrations.AlterModelOptions(
            name='infoslider',
            options={'verbose_name': 'слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'меню', 'verbose_name_plural': 'меню'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
