# Generated by Django 5.0.3 on 2024-03-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_entertainment_options_alter_infoslider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='description',
            field=models.TextField(verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='feature_image',
            field=models.ImageField(default='default-services.jpg', upload_to='entertainment/%Y/%m/%d', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='Цена за позицию'),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Названия'),
        ),
        migrations.AlterField(
            model_name='infoslider',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Описание слайда'),
        ),
        migrations.AlterField(
            model_name='infoslider',
            name='image_slider',
            field=models.ImageField(upload_to='slider_images/%Y/%m/%d', verbose_name='Изображения слайда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='feature_image',
            field=models.ImageField(default='default-services.jpg', upload_to='menu/%Y/%m/%d', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Цена за позицию'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Названия'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='services',
            name='feature_image',
            field=models.ImageField(default='default-services.jpg', upload_to='services/%Y/%m/%d', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='Цена за позицию/руб.'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Названия'),
        ),
    ]
